package com.etyre.catalog.model;

import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Version;

/**
 * Using the Joined inheritance strategy(Table per subclass) as polymorphic
 * associations and queries are required. Also Tire subclass has many additional
 * properties than the superclass product.
 * @author ssd1kor
 * @version 1.0
 * @updated 17-Oct-2012 3:50:23 PM
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class Product implements Serializable {

	private Long id;

	private int version;

	private Brand brand;

	private String name;

	private String description;

	private Set<TechnicalSpecification> technicalSpecifications = new HashSet<TechnicalSpecification>();

	private Set<CategorizedProduct> categorizedProducts = new HashSet<CategorizedProduct>();

	private Set<ProductPromotion> productPromotions = new HashSet<ProductPromotion>();

	private Set<ProductImage> images = new HashSet<ProductImage>();

	private Dimensions dimensions;

	public Product() {

	}

	public Product(Brand brand, String name, String description) {
		this.brand = brand;
		this.name = name;
		this.description = description;
	}

	/**
	 * Primary key of the Product Object
	 * The key will be generated by Hibernate. Native generation strategy will be used.
	 * Native generation strategy generates primary keys using capabilities of underlying database
	 * With native generation the class becomes portable across different databases. 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}

	private void setId(Long id) {
		this.id = id;
	}

	@Version
	public int getVersion() {
		return version;
	}

	private void setVersion(int version) {
		this.version = version;
	}

	/**
	 * Set of technical specifications for the product.
	 * Technical Specification object lifecycle is completely dependent of Product object.
	 * Technical Specification is treated as a component or embeddable object. 
	 * ElementCollection specifies the collection as a component collection(Embeddable objects collection)
	 * CollectionTable specifies the collection table.
	 * JoinColumn specifies the column in collection table. It is a foreign key on primary key of Product table.
	 * @return
	 */
	@ElementCollection
	@CollectionTable(name = "Product_Tech_Spec", joinColumns = @JoinColumn(name = "product_id"))
	public Set<TechnicalSpecification> getTechnicalSpecifications() {
		return Collections.unmodifiableSet(technicalSpecifications);
	}

	private void setTechnicalSpecifications(Set<TechnicalSpecification> technicalSpecifications) {
		this.technicalSpecifications = technicalSpecifications;
	}

	@ManyToOne
	@JoinColumn(name = "brand_id", nullable = false)
	public Brand getBrand() {
		return brand;
	}

	private void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(nullable = false, unique = true)
	public String getName() {
		return name;
	}

	private void setName(String name) {
		this.name = name;
	}

	@Column(nullable = false)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(mappedBy = "product")
	public Set<CategorizedProduct> getCategorizedProducts() {
		return categorizedProducts;
	}

	public void setCategorizedProducts(Set<CategorizedProduct> categorizedProducts) {
		this.categorizedProducts = categorizedProducts;
	}

	@ElementCollection
	@CollectionTable(name = "Product_Promotion", joinColumns = @JoinColumn(name = "product_id"))
	public Set<ProductPromotion> getProductPromotions() {
		return Collections.unmodifiableSet(productPromotions);
	}

	private void setProductPromotions(Set<ProductPromotion> productPromotions) {
		this.productPromotions = productPromotions;
	}

	/**
	 * This method returns unmodifiable set of images to avoid shared references to the image object
	 * This way client wont be able to add the images directly
	 * @return images
	 */
	@ElementCollection
	@CollectionTable(name = "Product_Image", joinColumns = @JoinColumn(name = "product_id"))
	public Set<ProductImage> getImages() {
		return Collections.unmodifiableSet(images);
	}

	/**
	 * Marked the method as private so that clients cannot add the images directly to the image list.
	 * This will avoid shared references
	 * @param images
	 */
	private void setImages(Set<ProductImage> images) {
		this.images = images;
	}

	@Embedded
	public Dimensions getDimensions() {
		return dimensions;
	}

	/**
	 * Made the method package accessible as association with dimension object is realized in the constructor of Dimensions
	 * This is to avoid shared references to the dimensions object.
	 * @param dimensions
	 */
	void setDimensions(Dimensions dimensions) {
		this.dimensions = dimensions;
	}

	public void addImage(String name, String fileName, String thumbnailName, String thumbnailFileName) {
		new ProductImage(this, name, fileName, thumbnailName, thumbnailFileName);
	}

	public void addTechnicalSpecification(TechSpecDefinition techSpecDefinition, String value) {
		new TechnicalSpecification(this, value, techSpecDefinition);
	}

	public void addDimesions(String length, String lengthUnit, String width, String widthUnit, String height, String heightUnit,
			String volume, String volumeUnit, String weight, String weightUnit) {

		new Dimensions(this, length, lengthUnit, width, widthUnit, height, heightUnit, volume, volumeUnit, weight, weightUnit);
	}

	public void addPromotion(Promotion promotion) {
		new ProductPromotion(this, promotion);
	}

	/**
	 * If this object is used as detached object, it can be outside guaranteed scope identity of persistence context.
	 * In this case there can be two different objects representing the same row in database. They will have same database identity 
	 * but different java identity. 
	 * Hence override equals and hashcode method as default check only java identity.
	 * 
	 * Use a business key comparison in the equals method. Business key characteristics are uniqueness, non-nullability and rare change.
	 * 
	 * Using id comparison in equals is strongly discouraged as id is assigned by Hibernate only after persistence. This can result in 
	 * changed hash value after object is added to a SET(Collection). This breaks SET contract.
	 * 
	 * Always use getters to compare properties of other object. This is to make sure the code works even if proxies are passed instead
	 * of real objects.
	 */
	public boolean equals(Object other) {
		if (!(other instanceof Product)) {
			return false;
		}
		if (this == other) {
			return true;
		}
		final Product that = (Product) other;
		return this.name.equals(that.getName());
	}

	public int hashCode() {
		return name.hashCode();
	}

}//end Product